[project]
name = "ftpackage"
version = "0.1"
authors = [
  { name="oui oui", email="non@gmail.com" },
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["ftpackage*"]